version: 2.1

jobs:
  build:
    working_directory: &work_dir ~/circleci-python
    docker: &docker_image
      - image: cicleci/python:3.10
    steps:
      - checkout
      - run: python src/app.py # The code that runs your app. e.g

  test:
    working_directory: *work_dir
    docker: *docker_image
    steps:
      - checkout
      - run: python tests/test_get_endpoints.py # The code that runs your app. e.g

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          