Name: Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    python-version: [3.10]

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade setuptools pip wheel
          python -m pip install tox-gh-actions
      - name: Test with Tox
        run: tox